[2025-02-28 15:16:35,840: INFO: main: wel to our log]
[2025-02-28 16:26:19,377: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 16:26:19,379: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 16:26:19,381: INFO: common: created directory at: artifacts]
[2025-02-28 16:26:19,381: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 16:26:19,382: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1loEKqZTz4w4AV_Gni296WaBD9Od2Xfk7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:30:36,417: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1loEKqZTz4w4AV_Gni296WaBD9Od2Xfk7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 16:51:07,357: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 16:51:07,358: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 16:51:07,359: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 16:51:07,359: INFO: common: created directory at: artifacts]
[2025-02-28 16:51:07,359: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 16:51:07,359: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1loEKqZTz4w4AV_Gni296WaBD9Od2Xfk7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:12:20,874: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 17:12:20,875: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 17:12:20,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 17:12:20,876: INFO: common: created directory at: artifacts]
[2025-02-28 17:12:20,876: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 17:12:20,876: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1loEKqZTz4w4AV_Gni296WaBD9Od2Xfk7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:22:00,565: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1loEKqZTz4w4AV_Gni296WaBD9Od2Xfk7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 17:22:07,091: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 18:10:23,139: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:11:25,830: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:11:25,833: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:11:25,833: INFO: common: created directory at: artifacts]
[2025-02-28 18:11:25,834: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-28 18:11:26,409: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-28 18:11:26,597: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 18:11:26,599: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 18:22:00,395: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 18:22:00,397: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:22:00,398: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:22:00,398: INFO: common: created directory at: artifacts]
[2025-02-28 18:22:00,398: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 18:22:00,398: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 18:23:04,394: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 18:23:04,738: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 18:23:04,738: INFO: main: *******************]
[2025-02-28 18:23:04,738: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 18:23:04,739: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:23:04,740: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:23:04,740: INFO: common: created directory at: artifacts]
[2025-02-28 18:23:04,740: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    prepare_base_model.main()
  File "/Users/kartikraturi/Desktop/DL project /Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2025-02-28 18:27:13,164: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 18:27:13,165: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:27:13,166: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:27:13,166: INFO: common: created directory at: artifacts]
[2025-02-28 18:27:13,166: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 18:27:13,166: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 18:27:36,458: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 18:27:36,815: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 18:27:36,815: INFO: main: *******************]
[2025-02-28 18:27:36,815: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 18:27:36,816: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:27:36,817: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:27:36,817: INFO: common: created directory at: artifacts]
[2025-02-28 18:27:36,817: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    prepare_base_model.main()
  File "/Users/kartikraturi/Desktop/DL project /Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2025-02-28 18:30:36,213: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 18:30:36,214: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:30:36,215: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:30:36,215: INFO: common: created directory at: artifacts]
[2025-02-28 18:30:36,215: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 18:30:36,215: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 18:31:41,764: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 18:31:42,097: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 18:31:42,097: INFO: main: *******************]
[2025-02-28 18:31:42,097: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 18:31:42,098: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:31:42,099: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:31:42,099: INFO: common: created directory at: artifacts]
[2025-02-28 18:31:42,099: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-28 18:31:43,034: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-28 18:31:43,121: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 18:31:43,123: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 18:31:43,225: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-28 18:55:24,416: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 18:55:24,419: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 18:55:24,421: INFO: common: created directory at: artifacts]
[2025-02-28 18:55:24,422: INFO: common: created directory at: artifacts/training]
[2025-02-28 19:22:52,337: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 19:22:52,338: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 19:22:52,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 19:22:52,340: INFO: common: created directory at: artifacts]
[2025-02-28 19:22:52,340: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 19:22:52,340: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 19:23:33,485: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 19:23:33,835: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 19:23:33,836: INFO: main: *******************]
[2025-02-28 19:23:33,836: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 19:23:33,837: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 19:23:33,838: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 19:23:33,838: INFO: common: created directory at: artifacts]
[2025-02-28 19:23:33,838: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-28 19:23:34,319: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-28 19:23:34,422: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 19:23:34,424: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 19:23:34,503: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-28 19:23:34,504: INFO: main: *******************]
[2025-02-28 19:23:34,504: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-28 19:23:34,505: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 19:23:34,505: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 19:23:34,505: INFO: common: created directory at: artifacts]
[2025-02-28 19:23:34,505: INFO: common: created directory at: artifacts/training]
[2025-02-28 19:23:41,897: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-28 20:22:03,251: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 20:22:03,254: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 20:22:03,255: INFO: common: created directory at: artifacts]
[2025-02-28 20:22:06,604: INFO: common: json file saved at: scores.json]
[2025-02-28 20:22:14,352: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 20:22:14,686: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmp4monhil8/model/data/model/assets]
[2025-02-28 20:41:08,693: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 20:41:08,697: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 20:41:08,698: INFO: common: created directory at: artifacts]
[2025-02-28 20:41:11,418: INFO: common: json file saved at: scores.json]
[2025-02-28 20:41:19,138: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 20:41:19,482: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmp_a6uueu4/model/data/model/assets]
[2025-02-28 20:44:20,421: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'timeout('The write operation timed out')': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow-artifacts/artifacts/8075253587384d7d865eb9ddc123065a/f7d0744bdcec46d892b5b32890b05c62/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-28 20:45:21,236: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 20:45:21,239: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 20:45:21,241: INFO: common: created directory at: artifacts]
[2025-02-28 20:45:23,905: INFO: common: json file saved at: scores.json]
[2025-02-28 20:45:32,723: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 20:45:33,076: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmpiitu3nnw/model/data/model/assets]
[2025-02-28 21:05:59,499: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:05:59,502: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:05:59,503: INFO: common: created directory at: artifacts]
[2025-02-28 21:06:02,175: INFO: common: json file saved at: scores.json]
[2025-02-28 21:06:32,258: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1737cc640>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:06:36,275: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1737ccb80>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:06:44,282: WARNING: connectionpool: Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1732991f0>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:07:06,929: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:07:06,931: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:07:06,932: INFO: common: created directory at: artifacts]
[2025-02-28 21:07:09,761: INFO: common: json file saved at: scores.json]
[2025-02-28 21:07:09,855: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x173972be0>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:07:13,858: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1739727f0>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:07:21,868: WARNING: connectionpool: Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x173919790>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:07:37,876: WARNING: connectionpool: Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1779ba460>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:08:09,883: WARNING: connectionpool: Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1779ba910>: Failed to resolve 'dagshub.com' ([Errno 8] nodename nor servname provided, or not known)")': /kartikraturi2/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2025-02-28 21:11:05,876: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:11:05,879: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:11:05,880: INFO: common: created directory at: artifacts]
[2025-02-28 21:11:08,408: INFO: common: json file saved at: scores.json]
[2025-02-28 21:11:16,682: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 21:11:16,985: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmpnm2ra9or/model/data/model/assets]
[2025-02-28 21:17:14,412: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:17:14,415: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:17:14,416: INFO: common: created directory at: artifacts]
[2025-02-28 21:17:16,957: INFO: common: json file saved at: scores.json]
[2025-02-28 21:17:25,022: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 21:17:25,342: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmpy5qss8oe/model/data/model/assets]
[2025-02-28 21:26:15,681: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:26:15,684: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:26:15,685: INFO: common: created directory at: artifacts]
[2025-02-28 21:26:18,314: INFO: common: json file saved at: scores.json]
[2025-02-28 21:26:25,948: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 21:26:26,311: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmpbwbyhxbr/model/data/model/assets]
[2025-02-28 21:53:19,379: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 21:53:19,380: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:53:19,381: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:53:19,381: INFO: common: created directory at: artifacts]
[2025-02-28 21:53:19,381: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 21:53:19,381: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 21:54:40,922: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 21:54:41,291: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 21:54:41,291: INFO: main: *******************]
[2025-02-28 21:54:41,291: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 21:54:41,292: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:54:41,293: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:54:41,293: INFO: common: created directory at: artifacts]
[2025-02-28 21:54:41,293: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-28 21:54:41,792: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-28 21:54:41,920: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 21:54:41,922: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 21:54:42,033: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-28 21:54:42,034: INFO: main: *******************]
[2025-02-28 21:54:42,034: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-28 21:54:42,035: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:54:42,035: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:54:42,035: INFO: common: created directory at: artifacts]
[2025-02-28 21:54:42,035: INFO: common: created directory at: artifacts/training]
[2025-02-28 21:54:51,060: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-28 21:54:51,060: INFO: main: *******************]
[2025-02-28 21:54:51,060: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-28 21:54:51,061: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:54:51,062: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:54:51,062: INFO: common: created directory at: artifacts]
[2025-02-28 21:54:53,581: INFO: common: json file saved at: scores.json]
[2025-02-28 21:54:53,581: INFO: common: json file saved at: scores.json]
[2025-02-28 21:54:53,581: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-28 21:58:46,783: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 21:58:46,785: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 21:58:46,785: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 21:58:46,785: INFO: common: created directory at: artifacts]
[2025-02-28 21:58:46,785: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 21:58:46,785: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 22:00:17,430: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 22:00:17,840: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 22:00:17,840: INFO: main: *******************]
[2025-02-28 22:00:17,840: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 22:00:17,842: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 22:00:17,842: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 22:00:17,842: INFO: common: created directory at: artifacts]
[2025-02-28 22:00:17,843: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-28 22:00:18,249: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-28 22:00:18,427: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 22:00:18,429: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-02-28 22:00:18,557: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-28 22:00:18,557: INFO: main: *******************]
[2025-02-28 22:00:18,557: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-28 22:00:18,558: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 22:00:18,558: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 22:00:18,558: INFO: common: created directory at: artifacts]
[2025-02-28 22:00:18,558: INFO: common: created directory at: artifacts/training]
[2025-02-28 22:00:32,495: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-28 22:00:32,496: INFO: main: *******************]
[2025-02-28 22:00:32,496: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-28 22:00:32,497: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 22:00:32,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 22:00:32,498: INFO: common: created directory at: artifacts]
[2025-02-28 22:00:34,894: INFO: common: json file saved at: scores.json]
[2025-02-28 22:00:34,894: INFO: common: json file saved at: scores.json]
[2025-02-28 22:00:34,894: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-28 22:02:08,922: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-02-28 22:02:08,924: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 22:02:08,925: INFO: common: created directory at: artifacts]
[2025-02-28 22:02:11,670: INFO: common: json file saved at: scores.json]
[2025-02-28 22:02:18,888: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-02-28 22:02:19,230: INFO: builder_impl: Assets written to: /var/folders/wv/7g72bbfd2rj_wgw6hwkcklgc0000gn/T/tmp5o0ny6yf/model/data/model/assets]
